hunt/models.py
from sqlalchemy import Integer, String, Column
from tibiacompendium.db import Base

class HuntingPlace(Base):
    __tablename__ = 'huntingplace'

    id = Column(Integer, primary_key=True)
    name = Column(String(250), nullable=False)
    exp_on_hour = Column(Integer, nullable=False)
    gold_on_hour = Column(Integer, nullable=True)
    hunt_type = Column(String(10), nullable=True, default='solo')
    description = Column(String, nullable=True, default='')
    rune = Column(String(50), nullable=True, default='')
    character_levels = Column(String(50), nullable=True, default='')
    equipment_with_resistance = Column(String(50), nullable=True, default='')

    def __init__(self, name=None):
        self.name = name

    def __repr__(self):
        return f'{self.name}'

__init__.py
from flask import Flask, render_template
from tibiacompendium.db import db_session

from tibiacompendium.city.views import city
from tibiacompendium.character.views import character
from tibiacompendium.hunt.views import hunt
from tibiacompendium.hunt.views_sql_alchemy import hunt_v2

app = Flask(__name__)
app.url_map.strict_slashes = False

# blueprints
app.register_blueprint(city)
app.register_blueprint(character)
app.register_blueprint(hunt)
app.register_blueprint(hunt_v2)


@app.route('/')
def home():
    return render_template('home.html')


# shutdown sql alchemy session
@app.teardown_appcontext
def shutdown_session(exception=None):
    db_session.remove()

character/views.py
import json
import urllib
from datetime import datetime
from flask import Blueprint, render_template, request

# use external API
character = Blueprint('character', __name__)

@character.route('/characters', methods=['GET'])
def render_character_template():
    character_data = []
    search_nickname = request.args.get('search')

    if search_nickname:
        nicknames = [search_nickname.replace(' ', '%20')]
    else:
        nicknames = ['Suri%20Firon', 'Dark%20Mortals', 'Lee%20Fighter']


    for nick in nicknames:
        try:
            response = urllib.request.urlopen('https://dev.tibiadata.com/v4/character/' + nick)
        except:
            return render_template('character.html', characters = [])
        else:
            data = response.read()
            json_data = json.loads(data)

            # get created dt
            if 'account_information' in json_data['character'] and 'created' in json_data['character']['account_information']:
                created = datetime.fromisoformat(json_data['character']['account_information']['created']).strftime("%d-%m-%Y %H:%M:%S")
            else:
                created = ''
            
            character_data.append({
                'name': json_data['character']['character']['name'],
                'level': json_data['character']['character']['level'],
                'vocation': json_data['character']['character']['vocation'],
                'world': json_data['character']['character']['world'],
                'residence': json_data['character']['character']['residence'],
                'achievement_points': json_data['character']['character']['achievement_points'],
                'last_login': datetime.fromisoformat(json_data['character']['character']['last_login']).strftime("%d-%m-%Y %H:%M:%S"),
                'created': created
            })

    return render_template('character.html', characters = character_data)

city/views.py
from flask import Blueprint, jsonify, request, abort, render_template
from tibiacompendium.db import mysql
from pymysql.err import IntegrityError, DataError

# simple API, using database cursor connection
city = Blueprint('city', __name__)

@city.route('/api/cities', methods=['GET'])
def get_cities():
    with mysql.cursor() as cursor:
        cursor.execute("SELECT id, name, added_in_version, is_premium_needed as pop FROM city")
        data = cursor.fetchall()
        cursor.close()
        return jsonify(data)
    
@city.route('/api/cities/<string:name>', methods=['GET'])
def get_city_by_name(name):
    with mysql.cursor() as cursor:
        cursor.execute("SELECT id, name, added_in_version, is_premium_needed as pop FROM city where name = %s", name)
        data = cursor.fetchall()
        cursor.close()
        return jsonify(data)
    
@city.route('/api/cities', methods=['POST'])
def post_city():
    try:
        name = request.json['name']
    except KeyError:
        abort(400, 'Field name is required')
    else:
        is_premium_needed = request.json.get('is_premium_needed', 1)
        added_in_version = request.json.get('added_in_version', '')
    
    with mysql.cursor() as cursor:
        try:
            cursor.execute("INSERT INTO city (name, is_premium_needed, added_in_version, added_in_version) VALUES (%s, %s)", 
                           (name, is_premium_needed, added_in_version))
            mysql.commit()
            return ({}, 204)
        except (IntegrityError, DataError) as e:
            abort(400, str(e))

@city.route('/cities', methods=['GET'])
def render_cities_template():
    with mysql.cursor() as cursor:
        cursor.execute("SELECT id, name, added_in_version, is_premium_needed as pop FROM city order by is_premium_needed, abs(added_in_version)")
        data = cursor.fetchall()
        return render_template('city.html', cities = data)

hunt/views.py
from flask import Blueprint, Response, request, render_template, url_for, redirect, abort
from pymysql.err import IntegrityError, DataError
from tibiacompendium.db import mysql
from tibiacompendium.hunt.helpers import count_exp_speed
from tibiacompendium.hunt.validators import validate_hunting_place_data

# API using database cursor connection
hunt = Blueprint('hunt', __name__)

@hunt.route('/hunting-places', methods=['POST'])
def add_huntingplace():
    errors, validated_data = validate_hunting_place_data(request.form)

    if errors:
        return render_template('huntingplace.html', errors=errors)
    else:
        exp_on_hour = count_exp_speed(validated_data.get('exp_on_hour'), validated_data.get('exp_factor'))
        with mysql.cursor() as cursor:
            try:
                cursor.execute(
                    """
                        INSERT INTO huntingplace 
                            (name, character_levels, hunt_type, exp_on_hour, gold_on_hour, 
                            rune, equipment_with_resistance, description)
                        VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
                    """, 
                    (validated_data.get('name'), validated_data.get('character_levels'), validated_data.get('hunt_type'), 
                     exp_on_hour, validated_data.get('gold_on_hour'),validated_data.get('rune'), 
                     validated_data.get('eq_with_resistance'), validated_data.get('description')
                    ))
                mysql.commit()
            except (IntegrityError, DataError) as e:
                abort(400, str(e))
            
            return redirect(url_for('hunt.render_huntingplaces_template', hunt_type=validated_data.get('hunt_type')))

# delete must be post method due html form restrictions
@hunt.route('/hunting-places/delete', methods=['POST'])    
def delete_huntingplace():
    id = request.form.get('id')

    with mysql.cursor() as cursor:
        try:
            cursor.execute(
                """
                    DELETE from huntingplace where id = %s
                """, 
                (id)
            )
        except (IntegrityError, DataError) as e:
            abort(400, str(e))
        else:
            mysql.commit()
    
    return redirect(url_for('hunt.render_huntingplaces_template'))

@hunt.route('/hunting-places', methods=['GET'])
def render_huntingplaces_template():
    hunt_type = request.args.get('hunt_type', 'solo')
    name = request.args.get('name', '')

    with mysql.cursor() as cursor:
        where_condition = "WHERE hunt_type = 'solo'" if hunt_type == 'solo' else "WHERE hunt_type = 'duo'"
        where_condition += f"AND name LIKE '%{name}%'"
        cursor.execute(
            """
            SELECT 
                COALESCE(name, ''), COALESCE(character_levels, ''), COALESCE(hunt_type, ''), COALESCE(exp_on_hour, ''), 
                COALESCE(gold_on_hour, ''), COALESCE(rune, ''), COALESCE(equipment_with_resistance, ''), COALESCE(description, ''),
                id
            FROM 
                huntingplace
            """ + where_condition + "order by exp_on_hour desc")
        data = cursor.fetchall()
        return render_template('huntingplace.html', hunting_places=data, hunt_type=hunt_type)

templates/character.html
<link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">

<a href="{{ url_for('home') }}">HOME</a>

<br><br>
{% block content %}
  <form method="get">
    <input name="search" id="search" placeholder="Enter a character name" required>
    <input type="submit" value="Search">
  </form>
{% endblock %}


<table class="styled-table">
    <thead>
        <tr>
            <th>Name</th>
            <th>Level</th>
            <th>Vocation</th>
            <th>World</th>
            <th>Residence</th>
            <th>Achievement points</th>
            <th>Last login</th>
            <th>Created date</th>
        </tr>
    </thead>
        {% for character in characters%}
        <td>{{character['name']}}</td>
        <td>{{character['level']}}</td>
        <td>{{character['vocation']}}</td>
        <td>{{character['world']}}</td>
        <td>{{character['residence']}}</td>
        <td>{{character['achievement_points']}}</td>
        <td>{{character['last_login']}}</td>
        <td>{{character['created']}}</td>
        </tr>
        {% endfor %}
</table>

templates/city.html
<link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">

<a href="{{ url_for('home') }}">HOME</a>

<table class="styled-table">
    <thead>
        <tr>
            <th>Name</th>
            <th>Added in version</th>
            <th>Premium</th>
        </tr>
    </thead>
        {% for city in cities%}
        <td>{{city[1]}}</td>
        <td>{{city[2]}}</td>
        <td>
            {% if city[3] %}
            <input disabled="disabled" type="checkbox" id="id_{{city[0]}}" name="checkbox" checked>
            {% else %}
                <input disabled="disabled" type="checkbox" id="id_{{city[0]}}" name="checkbox" >
            {% endif %}
        </td>
        </tr>
        {% endfor %}
</table>

templates/home.html
<link rel="stylesheet" href="{{ url_for('static', filename='home_style.css') }}">
<div class="grid-container">

    <a href="{{ url_for('city.render_cities_template') }}">
        <div class="grid-item">CITIES</div>
    </a>
    <a href="{{ url_for('character.render_character_template') }}">
        <div class="grid-item">CHARACTERS</div>
    </a>
    <a href="{{ url_for('hunt.render_huntingplaces_template') }}">
        <div class="grid-item">HUNTING PLACES</div>
    </a>
    <a href="{{ url_for('hunt_v2.render_huntingplaces_template') }}">
        <div class="grid-item">HUNTING PLACES V2</div>
    </a>

</div>

templates/huntingplace.html
<link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">

<a href="{{ url_for('home') }}">HOME</a>
<br><br>

<!-- filter fields -->
<form action="{{ url_for('hunt.render_huntingplaces_template') }}" method="get">
  <fieldset>
    <legend>Select hunt type:</legend>  
    
    <div>
      <input type="radio" id="solo" name="hunt_type" value="solo" {% if hunt_type == "solo" %}checked{% endif %}/>
      <label for="solo">Solo</label>
    </div>
  
    <div>
      <input type="radio" id="duo" name="hunt_type" value="duo"  {% if hunt_type == "duo" %}checked{% endif %}/>
      <label for="duo">Duo</label>
    </div>

    <div>
      <input name="name" id="name" placeholder="Enter a name">
    </div>

    <div>
      <button type="submit">Filter</button>
    </div>

  </fieldset>
</form>

<!-- table with data -->
<table class="styled-table">
    <thead>
        <tr>
            <th>Name</th>
            <th>Character levels</th>
            <th>Hunt type</th>
            <th>Exp[k/h][100%]</th>
            <th>Gold[k/h]</th>
            <th>Rune</th>
            <th>Equipment with resistance</th>
            <th>Description</th>
        </tr>
    </thead>
        {% for place in hunting_places%}
        <td>{{place[0]}}</td>
        <td>{{place[1]}}</td>
        <td>{{place[2]}}</td>
        <td>{{place[3]}}</td>
        <td>{{place[4]}}</td>
        <td>{{place[5]}}</td>
        <td>{{place[6]}}</td>
        <td>{{place[7]}}</td>
        </tr>
        {% endfor %}
</table>

<!-- form with field to add -->
  <form action="{{ url_for('hunt.add_huntingplace') }}" method="post">

    <input type="text" placeholder="Enter a name" id = "name" name="name" >
    <input type="text" placeholder="Enter a character levels" name="character_levels" >
    <select name="hunt_type" id="hunt_type">
      <option value="solo">Solo</option>
      <option value="duo">Duo</option>
    </select>
    <input type="number" placeholder="Enter a exp[k/h]" name="exp_on_hour" >
    <select name="exp_factor" id="exp_factor">
      <option value="100">100%</option>
      <option value="150">150%</option>
      <option value="200">200%</option>
      <option value="225">225%</option>
      <option value="300">300%</option>
      <option value="375">375%</option>
    </select>
    <input type="number" placeholder="Enter a gold[k/h]" name="gold_on_hour" >
    <input type="text" placeholder="Enter a rune" name="rune" >
    <input type="text" placeholder="Enter a equipment with resistance" name="eq_with_resistance" >
    <input type="text" placeholder="Enter a description" name="description" >

    <button type="submit" class="add-btn">Add</button>
  
    <br>
    {% if errors %}
      <label class="error-label"> {{errors}} </label>
    {% endif %}
    
  </form>

  <!-- delete section -->
  <form action="{{ url_for('hunt.delete_huntingplace') }}" method="post">

    <select name="id" id="deleteSelect">
      {% for place in hunting_places%}
        <option value="{{place[8]}}">{{place[0]}}</option>
      {% endfor %}
    </select>
    <button id="deleteBtn" type="submit" class="delete-btn" >Delete</button>

  </form>

templates/huntingplace_v2.html
<link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">

<a href="{{ url_for('home') }}">HOME</a>
<br><br>

<!-- filter fields -->
<form action="{{ url_for('hunt_v2.render_huntingplaces_template') }}" method="get">
  <fieldset>
    <legend>Select hunt type:</legend>  
    
    <div>
      <input type="radio" id="solo" name="hunt_type" value="solo" {% if hunt_type == "solo" %}checked{% endif %}/>
      <label for="solo">Solo</label>
    </div>
  
    <div>
      <input type="radio" id="duo" name="hunt_type" value="duo"  {% if hunt_type == "duo" %}checked{% endif %}/>
      <label for="duo">Duo</label>
    </div>

    <div>
      <input name="name" id="name" placeholder="Enter a name">
    </div>

    <div>
      <button type="submit">Filter</button>
    </div>

  </fieldset>
</form>

<!-- table with data -->
<table class="styled-table">
    <thead>
        <tr>
            <th>Name</th>
            <th>Character levels</th>
            <th>Hunt type</th>
            <th>Exp[k/h][100%]</th>
            <th>Gold[k/h]</th>
            <th>Rune</th>
            <th>Equipment with resistance</th>
            <th>Description</th>
        </tr>
    </thead>
        {% for place in hunting_places%}
        <td>{{place[0]}}</td>
        <td>{{place[1]}}</td>
        <td>{{place[2]}}</td>
        <td>{{place[3]}}</td>
        <td>{{place[4]}}</td>
        <td>{{place[5]}}</td>
        <td>{{place[6]}}</td>
        <td>{{place[7]}}</td>
        </tr>
        {% endfor %}
</table>

<!-- form with field to add -->
  <form action="{{ url_for('hunt_v2.add_huntingplace') }}" method="post">

    <input type="text" placeholder="Enter a name" id = "name" name="name" >
    <input type="text" placeholder="Enter a character levels" name="character_levels" >
    <select name="hunt_type" id="hunt_type">
      <option value="solo">Solo</option>
      <option value="duo">Duo</option>
    </select>
    <input type="number" placeholder="Enter a exp[k/h]" name="exp_on_hour" >
    <select name="exp_factor" id="exp_factor">
      <option value="100">100%</option>
      <option value="150">150%</option>
      <option value="200">200%</option>
      <option value="225">225%</option>
      <option value="300">300%</option>
      <option value="375">375%</option>
    </select>
    <input type="number" placeholder="Enter a gold[k/h]" name="gold_on_hour" >
    <input type="text" placeholder="Enter a rune" name="rune" >
    <input type="text" placeholder="Enter a equipment with resistance" name="eq_with_resistance" >
    <input type="text" placeholder="Enter a description" name="description" >

    <button type="submit" class="add-btn">Add</button>
  
    <br>
    {% if errors %}
      <label class="error-label"> {{errors}} </label>
    {% endif %}
    
  </form>

  <!-- delete section -->
  <form action="{{ url_for('hunt_v2.delete_huntingplace') }}" method="post">

    <select name="id" id="deleteSelect">
      {% for place in hunting_places%}
        <option value="{{place[8]}}">{{place[0]}}</option>
      {% endfor %}
    </select>
    <button id="deleteBtn" type="submit" class="delete-btn" >Delete</button>

  </form>